### ISSUE TITLE
$route (/URL) or identifier change not watched

### ISSUE THREAD

**Issue by soichih** [ktquez/vue-disqus#11]
I am displaying vue-disqus inside a content where I must update the page identifier for vue-disqus without re-creating the vue-disqus component. When I change the ID that I am passing to vue-disqus, it doesn't update the disqus page, it's stuck with page content for the old ID.

Same goes for the route change. When I don't specify identify, I believe it's using URL as identifier by default, but if I modify the URL, it's not updating the disqus content.

Can vue-disqus be updated to watch for these changes?

**Comment by ktquez** [comment]
I'll make tests and changes to suit this problem.
Thanks

**Comment by jctiru** [comment]
I'm also having this problem. When I'm changing routes it still uses the identifier used from the previously loaded resource. But when the resource gets updated (upon switching route where the resource is fetched via axios), the disqus component won't reload. I need to hit page refresh to reload the component or go back and go to that route again. Is there a workaround while this problem exists? Thanks!

**Comment by amicablecoder** [comment]
instead of calling 
mounted () {
      if (window.DISQUS) {
        this.reset(window.DISQUS)
        return
      }
      this.init()
    },
use:
    created () {
      this.init()
    }
as the life cycle method in Vue-DIsqus.vue file.

and call 
<vue-disqus shortname="your disqus shortname" :identifier="k" :url="http://your.example.com/path/k"></vue-disqus>

where k is your unique identifier to create unique threads.

**Comment by ktquez** [comment]
@soichih 
When the URL changes you can try to use $refs to trigger the reset method of the vue-disqus.

```vue
<vue-disqus 
  ref="disqus" 
  shortname="your_shortname_disqus" 
  :identifier="page_id" 
  :url="url" />
```

```javascript

watch: {
  url (value) {
    this.$refs.disqus.reset(window.DISQUS)
  }
}

```

I have not tested it, but if Disqus supports it, I think it will work.

**Comment by soichih** [comment]
Why can't this watch be implemented inside the vue-disqus? I think it should automatically reset if it sees the url changing.

**Comment by ktquez** [comment]
@soichih 

Yes, it will be included in the next versions.
But at the moment I'm a little out of time to upgrade, but for now this option can help until the new version is released.

Thank you

**Comment by soichih** [comment]
@ktquez Ah, OK. That sounds good.

I did try the watch for identifier and run `this.$refs.disqus.reset()`. The disqus seems to get reloaded, but it seems to be loading with wrong identifier; I sometimes see threads that belongs to a wrong key.. I could be doing something wrong, but just fyi.
