### ISSUE TITLE
Failed to load resource: net::ERR_CERT_COMMON_NAME_INVALID

### ISSUE THREAD

**Issue by harishankards** [ktquez/vue-disqus#15]
Hey guys, 

First of all thanks for the great work. I tried integrating with my project like below:
// inside template
` <vue-disqus shortname="student-burger.disqus.com"></vue-disqus> `

// Inside script
`  import VueDisqus from 'vue-disqus/VueDisqus.vue' `
and 
```   
components: {
      VueDisqus
    },
```

I'm getting this error in the console as `Failed to load resource: net::ERR_CERT_COMMON_NAME_INVALID ` from `embed.js`

I gave only shortname as that is only mandatory. 

Thanks in advance

**Comment by ktquez** [comment]
I'll do some tests tomorrow and see what can be.
Thanks @harishankards

**Comment by harishankards** [comment]
Great. Thanks, @ktquez. Looking forward

**Comment by ktquez** [comment]
@harishankards 
I tested it and everything is ok with the plugin
This problem seems to be your browser, I found a link about this error.
https://productforums.google.com/forum/#!msg/chrome/95NrJOxJKSg/mlThr4wbAwAJ

Any question just open this issue again

**Comment by harishankards** [comment]
Hey @ktquez! Thanks for the help. Fixed the issue.
