### ISSUE TITLE
ERROR in 1.client-bundle.60090d500a0bfc6d85e5.js from UglifyJs Unexpected token: punc (() [1.client-bundle.60090d500a0bfc6d85e5.js:1022,10]

### ISSUE THREAD

**Issue by wsdo** [ktquez/vue-disqus#16]
![image](https://user-images.githubusercontent.com/9738969/38919561-7ed4a570-4323-11e8-8273-75eb5386dc84.png)
ERROR in 1.client-bundle.60090d500a0bfc6d85e5.js from UglifyJs
Unexpected token: punc (() [1.client-bundle.60090d500a0bfc6d85e5.js:1022,10]

**Comment by ktquez** [comment]
I'm going to do some testing tomorrow and update the dependencies, okay?
Thanks @wsdo

**Comment by ktquez** [comment]
@wsdo 
vue-disqus have no dependencies.

This problem is with Uglify.js, please update the package or remove the node_modules/ directory and install again.

**Comment by BenjaminWaye** [comment]
Did removing the node_modules directory work? I tried that still get the same error and updating Uglify.js doesn't help

**Comment by ktquez** [comment]
@BenjaminWaye 
Import the component to see if it works
`import VueDisqus from 'vue-disqus/vue-disqus.vue'`

**Comment by BenjaminWaye** [comment]
> This dependency was not found:
> * vue-disqus/vue-disqus.vue in ./src/main.js
> To install it, you can run: npm install --save vue-disqus/vue-disqus.vue

I have run npm install vue-disqus

**Comment by ktquez** [comment]
@BenjaminWaye 
Sorrry, try it `import VueDisqus from 'vue-disqus/dist/vue-disqus.vue'`

**Comment by BenjaminWaye** [comment]
Now build goes fine however get this error instead [Vue warn]: Unknown custom element: <vue-disqus>, so the vue-disqus is not loading.

Npm run dev runs fine, it is odd that only npm run build doesn't work
