### ISSUE TITLE
How to embed vue-disqus in multiple posts in a single page?

### ISSUE THREAD

**Issue by harishankards** [ktquez/vue-disqus#17]
Hi,
I'm trying to embed Disqus in my project, which is a kinda social network. 
In my Newsfeed page, there will be multiple posts which will have the comments section. There, for every post, I need to embed Disqus. 

When I put the code, only for the first post, Disqus is embedded. And for the rest of the posts, it's not.

How do I achieve this?

Thanks in advance!

**Comment by ktquez** [comment]
@harishankards 
I think Disqus only supports one Disqus module per page.

**Comment by harishankards** [comment]
Got it. Thanks @ktquez
