### ISSUE TITLE
Change ready hook to mounted

### ISSUE THREAD

**Issue by Smallpath** [ktquez/vue-disqus#2]
Hi : 
    Thanks for your work.  But it seems that vue-disqus is not working with vue2.0 since the `ready` hook is replaced by `mounted`. Now I use following code which works but it would be nicer if you correct it in the vue-disqus  :+1: 
```
import Disqus from 'vue-disqus'

Disqus.mounted = Disqus.ready;
```

**Comment by ktquez** [comment]
@Smallpath 
Was upgraded two days ago, take a look at v2.0.0
https://github.com/ktquez/vue-disqus/blob/v2.0.0/vue-disqus.vue#L13

Thanks for the feedback.

**Comment by Smallpath** [comment]
Wow, sorry for not checking the tags.

**Comment by ktquez** [comment]
@Smallpath 
No need to apologize, I thank you for having warned me.
