### ISSUE TITLE
Getting same comments on all pages

### ISSUE THREAD

**Issue by prajjwaldimri** [ktquez/vue-disqus#20]
Hi, I was trying to integrate vue-disqus into my application but I am getting the same comments on every page.

This is how I am implementing vue-disqus in the app.
`vue-disqus(shortname="my_short_name" :identifier="disqus_id" :url="disqus_url")`

The disqus_id and disqus_url variables are set during the created() hook.

Can you suggest me any fixes for this? Thanks.

**Comment by ktquez** [comment]
Hi, checks if the identifier and URL are changing on each page.

**Comment by prajjwaldimri** [comment]
Yup. Everytime a new page loads the variables, to which the identifier and url are binded to, are different.

**Comment by ktquez** [comment]
Probably the "vue-disqus component" are being built before the data is available.

Uses a "v-if" in the component to only be created when "disqus_url" is available.

**Comment by prajjwaldimri** [comment]
Fixed. Thanks :+1:
