### ISSUE TITLE
Unable to load disqus

### ISSUE THREAD

**Issue by Sidney-Dev** [ktquez/vue-disqus#24]
I am trying to use disqus in my Laravel + VueJs application and added this in my app.js:

```
import VueDisqus from 'vue-disqus';
Vue.use(VueDisqus);
```
My Single.vue looks like this:

```
<div class="col-sm-9">
  <h1>{{ post.title }}</h1>
  <p>Posted By <strong>{{post.user.name}}</strong> {{ post.created_at | moment("from", "now", true) }} ago</p>
  <article v-html="post.description"></article>
   <div class="comments">
      <vue-disqus shortname="your_shortname_disqus" :identifier="post.id" url="sidneylab.local/post/"></vue-disqus>
    </div>
</div>
```
No errors are shown when I view the page but I see a message saying " Unable to load disqus "

Anything wrong am possibly doing?

**Comment by ktquez** [comment]
@Sidney-Dev 
You need to set your shortname disqus.

e.g.
`<vue-disqus shortname="user125" :identifier="post.id" url="sidneylab.local/post/"></vue-disqus>`

**Comment by Sidney-Dev** [comment]
I saw my disqus name on their website and now am using it.

    <vue-disqus shortname="sidneyblog-local-1" :identifier="post.id" url="sidneylab.local/post/"></vue-disqus>

But I still see the same message

**Comment by ktquez** [comment]
@Sidney-Dev 
I think this is some past configuration in prop `url`
Try to use a `url with protocol` or just not inform the url, as the vue-disqus itself already automatically takes the current url of the page.

e.g. 
`url="http://sidneylab.local/post/"`

**Comment by Sidney-Dev** [comment]
Actually it was working when I added the shortname given by disqus, I just had to clear my browser cache and it now works.
Appreciate the support.
