### ISSUE TITLE
VueDisqus, Building using latest VueCLI and Internet Explorer 11

### ISSUE THREAD

**Issue by mjruschak** [ktquez/vue-disqus#29]
There may be a bug with the vue-disqus plugin.  On my system it errors out around this line in IE 11.  Any suggestions?  Awesome plugin btw!

`
mounted () {
      if (window.DISQUS) {
`

**Comment by mjruschak** [comment]
So I think VueCli by default does not transpile node modules.  Therefore Internet Explorer 11 cannot understand this shorthand syntax.  I have not yet figured out a way to resolve this yet.  If I add VueDisqus to the transpileDependencies list it does not seem to work.  I need to learn more about how this works.  Let me know if anyone else who has had this issue has any suggestions.

**Comment by 3rdp** [comment]
@mjruschak Is your issue resolved yet? Do you have the error message the Internet Explorer produced arong that line of code? And can you share some details about how did you configure VueCli?

**Comment by mjruschak** [comment]
That is correct I did have an error message along that line of code.  "Expected :"

I believe the plugin would need to be updated to support Babel 7 but I am not a Babel expert so not entirely sure.  VueCli is configured to use Babel for my project.  VueCli uses Babel 7 which uses the new babel-config.js format.  I have reason to believe this is why transpileDependencies for the vue config is not working right for this plugin.  There are a lot of plugins out there that support older versions of Babel still.  I found out this was not the only Vue plugin having the problem.  I only had one Vue plugin work correctly.

I believe Babel should Transpile the line with the error to be like this

mounted: function()

Anyways I ultimately decided not to support IE 11.  I have just had it with that browser and most of the customers using the web site we upgraded to use Vue do not use it anyway.  Only had a few support requests and we just tell them to use a different browser.

If I wanted to fix it I could probably pull the .vue file from node_modules into the application directory.  This way Babel would likely transpile it correctly.  

Otherwise this plugin may need to be updated to support the new Babel version but again I want to reiterate I do not know that for sure.  Not a Babel expert.

**Comment by ktquez** [comment]
Run a test using `import VueDisqus from 'vue-disqus/dist/vue-disqus.vue'`

**Comment by mjruschak** [comment]
When I do that it says I did not register the component correctly.

**Comment by mjruschak** [comment]
Also your solution helped me fix a few other plugins by importing from dist.  Just does not work for VueDisqus.  I should point out that even if it did import the syntax is still not going to work in IE 11.  It needs to be run through Babel somehow...

**Comment by ktquez** [comment]
vue-disqus will go through a refactory and I will correct these problems, as soon as I have a new version, I hereby communicate you here.

**Comment by oouxx** [comment]
Hello, the ":identifier" does not work.I am tring render the same component with different routers

[console_log](https://user-images.githubusercontent.com/31833929/49352688-36676900-f6f4-11e8-9890-577967893ab9.png)

**Comment by ktquez** [comment]
@mjruschak 

VueDisqus [v4](https://github.com/ktquez/vue-disqus/releases/tag/v4.0.0), can you check if the error persist?
