### ISSUE TITLE
Prevent Disqus section from being embedded on the page when vue-disqus component isn't currently rendered on the page

### ISSUE THREAD

**Issue by Arkeetina** [ktquez/vue-disqus#30]
I am having the following issue, there are several sections in my app, which you can switch from via menu, one of them being Disqus comment section.

When I quickly switch from this comment section to any other section, there is no 'container' for disqus being embed to, and it throws the following error: 
 `Uncaught TypeError: Cannot read property 'appendChild' of null embed.js:35`
From what I am seeing now in `vue-disqus.vue`, there is no check for container element existing on the page, so I assume that might be the issue for this error being thrown. 

If I am being wrong, how can I fix it?

**Comment by ktquez** [comment]
I will do some tests.

**Comment by Arkeetina** [comment]
@ktquez looks like no, and like something I should have tried. Thank you!

**Comment by jjoek** [comment]
@ktquez 
use v-if to check for what exactly. Because I am also getting same comments on all posts yet there is a unique identifier and unique url which actually update upon each page load.

**Comment by oezkancodes** [comment]
> I am having the following issue, there are several sections in my app, which you can switch from via menu, one of them being Disqus comment section.
> 
> When I quickly switch from this comment section to any other section, there is no 'container' for disqus being embed to, and it throws the following error:
> `Uncaught TypeError: Cannot read property 'appendChild' of null embed.js:35`
> From what I am seeing now in `vue-disqus.vue`, there is no check for container element existing on the page, so I assume that might be the issue for this error being thrown.
> 
> If I am being wrong, how can I fix it?

This issue is still not solved. I get the same error.
