### ISSUE TITLE
Shouldn't the dist files be in ES5?

### ISSUE THREAD

**Issue by pxwee5** [ktquez/vue-disqus#32]
A lot of people use `exclude: /node_module/` in their .js and .vue rules. And the arrow functions aren't transpiled into ES5 code. 

Then we get the punc error from uglify. `Unexpected token: punc (()...`

REF: https://github.com/ktquez/vue-disqus/issues/9

**Comment by ktquez** [comment]
@pxwee5 
I will do a refactory on this plugin and fix this.
Thanks for the feedback

**Comment by zangxx66** [comment]
Me too.I can't post files to my server right now.

**Comment by zangxx66** [comment]
I think your js file has some errors,you may need rebuild it ,if I reference vue file it is ok.

**Comment by ktquez** [comment]
@zangxx66 

VueDisqus [v4](https://github.com/ktquez/vue-disqus/releases/tag/v4.0.0), can you check if the error persist?

**Comment by ktquez** [comment]
If the problem persists, feel free to reopen that issue.
