### ISSUE TITLE
HTTP 500 issue

### ISSUE THREAD

**Issue by matthew-inamdar** [ktquez/vue-disqus#33]
Hey there!

I've not used Disqus before so forgive me if I'm missing something obvious.

I've placed this component on the blog post pages on a site and it seems to be loading and working fine. However in the console we are getting 2 errors for this URL (replaced some parameters with xxx for confidentiality):

```
https://links.services.disqus.com/api/ping?format=jsonp&key=xxx&loc=https%3A%2F%2Fstaging.lessons4less.co.uk%2Fblog%2Fbd2b0cae-1f12-4b49-aadd-23a9570ad2d0&subId=xxx&v=1&jsonp=xxx
```

They seem to be linked:
• 404
• xxx has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource

I've already added the domain ([staging.lessons4less.co.uk](https://staging.lessons4less.co.uk)) to the "Trusted Domains" for the site settings.

Any help is greatly appreciated!

Thanks!

### Update 1: 

It seems like the CORS issue is linked to the 404.

The server seems to respond with a 404 before being able to set the CORS headers. So the CORS issue can potentially be ignored.

It seems the issue is primarily the 404!

### Update 2:

Without making any code changes, I'm now getting a HTTP 500 error instead of a 404. This has caused the CORS issue to disappear, confirming my suspicions in update 1. Any idea why `https://links.services.disqus.com/api/ping` would give me a 500?

I'm now starting to wonder if this issue is on the Disqus side?

**Comment by hunterliu1003** [comment]
I have the same problem

**Comment by matthew-inamdar** [comment]
Updated original issue!

**Comment by matthew-inamdar** [comment]
Added further update the original issue!

**Comment by matthew-inamdar** [comment]
Fixed the issue! It's on the Disqus side. See this comment for the fix: http://disq.us/p/15grc6q
