### ISSUE TITLE
TypeError: b.component is not a function

### ISSUE THREAD

**Issue by mittalyashu** [ktquez/vue-disqus#34]
I am getting this error when I use `import VueDisqus from 'vue-disqus'`

![image](https://user-images.githubusercontent.com/29014463/56853611-f4132280-6947-11e9-9f9b-644f2ed49a05.png)

and when I use this `import VueDisqus from 'vue-disqus/dist/vue-disqus.vue';`, I get this error

![image](https://user-images.githubusercontent.com/29014463/56853614-01301180-6948-11e9-9693-2f0077ae76e0.png)

**Comment by RomanNagornyi** [comment]
I have the same error

**Comment by ktquez** [comment]
Can you reproduce this project online?

**Comment by sheikh005** [comment]
@mittalyashu are you able to solve the error?

**Comment by mittalyashu** [comment]
Sorry, I didn't tried after that.

**Comment by sheikh005** [comment]
> Sorry, I didn't tried after that.

So which method you used to use disqus?

**Comment by safan41** [comment]
I ran into this error if I imported `vue-disqus` by doing this:
```js
import VueDisqus from 'vue-disqus'

export default {
  components: {
    VueDisqus,
    ...
  }, 
  ...
}
```
instead of the way instead of the way it was showed in the README.

**Comment by ktquez** [comment]
VueDisqus [v4](https://github.com/ktquez/vue-disqus/releases/tag/v4.0.0), can you check if the error persist?

**Comment by ktquez** [comment]
If the problem persists, feel free to reopen that issue.
