### ISSUE TITLE
Erro ao gerar thumbnail

### ISSUE THREAD

**Issue by allanadriano** [ktquez/vue-disqus#38]
Ao tentar compartilhar o conteúdo no Facebook usando o disqus está ocorrendo o seguinte erro;

![image](https://user-images.githubusercontent.com/44995459/77217326-65c80200-6b00-11ea-9382-f142fcfea610.png)

Todas as meta tags estão configuradas corretamente;

**Comment by ktquez** [comment]
Fala @allanadriano blz

Lancei a [v4](https://github.com/ktquez/vue-disqus/releases/tag/v4.0.0) do VueDisqus, tentei através das documentações e fóruns, mas vi que esse erro ocorre e que não tem uma solução direta para isso.

Pelo que vi se você tiver feito algum comentário via localhost para o shortname usado, ele dará esse erro. Então uma solução seria usar um shortname para testes locais e só usar o shortname real em produção.

Também vi que existe como migrar os domínios, mas não me aprofundei sobre:
https://joejoomla.com/sound-off/167-what-to-do-when-your-disqus-comments-link-to-the-wrong-url.html

Enfim, se eu encontra uma solução que possa ser resolvida no componente, reabro e submeto uma nova versão.

Obrigado por usar.

**Comment by allanadriano** [comment]
Olá @ktquez,
Realmente tinha usado o shotname em alguns testes locais, ao excluir do disqus o shortname em questão e apenas recria-lo o erro ao gerar a thumbnail sumiu;

Meus agradecimentos, obrigado!

**Comment by ktquez** [comment]
Excelente @allanadriano.
Obrigado por contar como resolveu, também irei fazer o mesmo.

---

Excellent @allanadriano.
Thanks for telling me how to solve, I will also do the same.
