### ISSUE TITLE
Prop for light/dark color scheme

### ISSUE THREAD

**Issue by mzhukovs** [ktquez/vue-disqus#39]
Thanks for this library.

I have an app that has a theme switcher for user to pick between light and dark mode.

Looks like in admin settings in Disqus one can select auto or pick a light or dark based Disqus view. Wondering if it possible to update the library with a prop for this such that we could update on app dynamically. Would be an awesome feature.

**Comment by ktquez** [comment]
You read my mind.

I'm also going through this using [@vue-a11y/dark-mode](https://github.com/vue-a11y/vue-dark-mode) on my blog.

I will update yes, thanks for the suggestion.

As soon as I release an updated version, I'll let you know here.

**Comment by ktquez** [comment]
@mzhukovs 

VueDisqus [v4](https://github.com/ktquez/vue-disqus/releases/tag/v4.0.0) released!

I exposed a method to reset the embed, so you can run `this.$disqus.reset()` when there is a change in the theme of the app.

To learn more you can access the [reset documentation](https://ktquez.github.io/vue-disqus/reset.html).

**Comment by mzhukovs** [comment]
@ktquez this appears to be working only if the reset is triggered away from the page? Meaning, if we are on a page that has the Disqus component and we change the theme to dark and call reset(), it won't work. Are you seeing the same thing?

**Comment by ktquez** [comment]
Can you reproduce this online?

---

In my app, I needed to do this:

```js
if (this.$disqus.reset) this.$disqus.reset()
```

Due to the lazy load, it may be that the disqus is not yet loaded on the page, I check if the reset method has already been registered.
