### ISSUE TITLE
Override identifier in Disqus component

### ISSUE THREAD

**Issue by bbedward** [ktquez/vue-disqus#41]
It seems like the <Disqus /> component always uses the same identifier:

```javascript
(this.$route.path || window.location.pathname)
```

Our project uses localization via nuxt-i18n/vue-i18n so the path will differ for different languages. We'd like to have the same comment thread for any locale.

It would be nice to be able to override identifier in the <Disqus> component

**Comment by ktquez** [comment]
Sorry for delay.

You can use the `pageConfig` prop, using the `location` property, for example:

```
<Disqus shortname='your_shortname_disqus' :pageConfig="{ identifier: 'yout_unique_identifier' }" />
```

**Comment by neel** [comment]
I am getting 

> There was a problem with the Disqus configuration. TypeError: Cannot read property 'path' of undefined

near `this.$route.path`

**Comment by bbedward** [comment]
Thanks @ktquez that seems to work fine
