### ISSUE TITLE
After the Nuxt SSR, the SPA mode reload

### ISSUE THREAD

**Issue by pang-lee** [ktquez/vue-disqus#45]
Hello, @ktquez , I am wondering whether the Disqus support client side reload or render?

By the way I still can't use the this.$disqus.reset ( will output .rest is not a function ) --> I heard that this can do the reload, might be the function what I am expected?

And I do set up the URL and Identifier to every post by using :url and :identifier.  ( I see it change when I click the different post )

In documentation the :pageConfig did not work in my case.

Could you give me some suggestion of how to make Disqus render for each post when I click the comment button ( or do the reload ) instead of render when I route to that page?

which means like this:

![image](https://user-images.githubusercontent.com/13313753/87818564-59309c00-c89d-11ea-8146-138ec219495e.png)

![image](https://user-images.githubusercontent.com/13313753/87815473-3ea7f400-c898-11ea-99ea-a4f84439313b.png)

![image](https://user-images.githubusercontent.com/13313753/87815837-e4f3f980-c898-11ea-8739-8d7a5220287d.png)

![image](https://user-images.githubusercontent.com/13313753/87816539-1620f980-c89a-11ea-8012-859f0adb05af.png)

![image](https://user-images.githubusercontent.com/13313753/87817331-58970600-c89b-11ea-8b2e-fd6c9ad453e9.png)

**Comment by ktquez** [comment]
@pang-lee 
Can you reproduce this example online?
Or Share a repository so we can see the code?

It will be easier to help you.
