### ISSUE TITLE
Vue 3.0 compatibility 

### ISSUE THREAD

**Issue by cjblomqvist** [ktquez/vue-disqus#47]
Hi! Does vue-disqus work with Vue 3.0? 🙂

Thanks for your hard work!

**Comment by ktquez** [comment]
Yes, I do.
I just don't have a date for that, but I'm focused on releasing a version with Vue3 support next month.

**Comment by Gardamuse** [comment]
What is the status on Vue3 support currently? Would love to use this in my project.

**Comment by ktquez** [comment]
@Gardamuse 

Yes, it's in the plans, it's already in the queue.

I am currently creating a version of [vue-axe](https://github.com/vue-a11y/vue-axe-next) for Vue 3, and soon I will be doing the same with vue-disqus.

**Comment by superdiazzz** [comment]
> @Gardamuse
> 
> Yes, it's in the plans, it's already in the queue.
> 
> I am currently creating a version of [vue-axe](https://github.com/vue-a11y/vue-axe-next) for Vue 3, and soon I will be doing the same with vue-disqus.

I hope it will be release... I can't wait for that 😄

**Comment by ktquez** [comment]
Sorry guys, I had some family problems earlier this year, but I'll be back next month and will update to Vue 3.

**Comment by superdiazzz** [comment]
> Sorry guys, I had some family problems earlier this year, but I'll be back next month and will update to Vue 3.

Hi @ktquez  hope you will be okay, may i know status for vue 3?

**Comment by ktquez** [comment]
Hi @superdiazzz 

I started work on a version compatible with Vue.js 3 in the [next](https://github.com/ktquez/vue-disqus/tree/next) branch.

As soon as it's done, I'll let you know here.

**Comment by superdiazzz** [comment]
> Hi @superdiazzz
> 
> I started work on a version compatible with Vue.js 3 in the [next](https://github.com/ktquez/vue-disqus/tree/next) branch.
> 
> As soon as it's done, I'll let you know here.

Hi @ktquez does library for vue 3 ready to use?

**Comment by ktquez** [comment]
Hi @superdiazzz @cjblomqvist @Gardamuse 

Currently, I would recommend everyone to use [@vueuse/head](https://github.com/vueuse/head) they are doing an amazing job, but also the [vue-meta@next](https://github.com/nuxt/vue-meta/tree/next) can be more compatible with the vue-head, anyway, both are excellent and currently supported for Vue 3.

Sorry for the delay, I still intend the vue-head with support for Vue 3, but without prediction at the moment, I will try in my spare time to work on this new version later this semester to have something in the next.

Thanks

**Comment by superdiazzz** [comment]
@ktquez i am looking for social response third party. Can you explain to me, relate of @vueuse/head and vue-disqus? sorry am very2 new about this

**Comment by ktquez** [comment]
@superdiazzz 
I commented in the wrong place, I thought it was the vue-head repository, sorry 🙆‍♂️.

**Comment by superdiazzz** [comment]
> @superdiazzz
> I commented in the wrong place, I thought it was the vue-head repository, sorry 🙆‍♂️.

I see. No problem. So, May i know how far this goes?

**Comment by ktquez** [comment]
I already made a version compatible with [Vue 3](https://github.com/ktquez/vue-disqus/tree/next), but I still haven't had time to create the documentation.

I will publish it in the "next" tag, which can be downloaded through:

```bash
npm install -S vue-head@next
# or
yarn add vue-head@next
```

However, not much has changed, but I will try to create a quick README explaining how to install and use it.

**Comment by superdiazzz** [comment]
> I already made a version compatible with [Vue 3](https://github.com/ktquez/vue-disqus/tree/next), but I still haven't had time to create the documentation.
> 
> I will publish it in the "next" tag, which can be downloaded through:
> 
> ```shell
> npm install -S vue-head@next
> # or
> yarn add vue-head@next
> ```
> 
> However, not much has changed, but I will try to create a quick README explaining how to install and use it.

did you mean, vue-disqus@next ?

**Comment by ktquez** [comment]
@superdiazzz 

Sorry, that's right `vue-disqus@next`

**Comment by ktquez** [comment]
VueDisqus for Vue 3 is out 🎉🎉

- [How to install and setup](https://ktquez.github.io/vue-disqus/setup-v3.html#installation)

Thanks guys
