### ISSUE TITLE
Uncaught TypeError: cyclic object value

### ISSUE THREAD

**Issue by michidk** [ktquez/vue-disqus#51]
I get the following error:
```
Uncaught TypeError: cyclic object value
    sendMessage http://<my-id>.disqus.com/embed.js:44
    getInstanceOrLoad http://<my-id>.disqus.com/embed.js:45
    e http://<my-id>.disqus.com/embed.js:44
    g http://<my-id>.disqus.com/embed.js:44
    m http://<my-id>.disqus.com/embed.js:44
    trigger http://<my-id>.disqus.com/embed.js:44
    init http://<my-id>.disqus.com/embed.js:44
    m http://<my-id>.disqus.com/embed.js:44
    trigger http://<my-id>.disqus.com/embed.js:44
    ia http://<my-id>.disqus.com/embed.js:44
```
when clicking on this button:
![image](https://user-images.githubusercontent.com/3979930/103587701-1c5a6f00-4ee8-11eb-9220-1fba4a2e34c6.png)
Afterward, the cursor can't click or mark anything.

I am directly importing vue-disqus into the component, like so:
```
import { Disqus } from "vue-disqus";
export default {
  name: "Part",
  components: {
    Disqus,
  },
...
```

Edit: Also happened when importing this component, globally.

**Comment by ktquez** [comment]
@michidk 

Did you manage to solve it?

**Comment by michidk** [comment]
@ktquez No, I ended up not using Disqus

**Comment by ktquez** [comment]
I think it is a problem in the disqus script.
