### ISSUE TITLE
Few ideas

### ISSUE THREAD

**Issue by maxorlovsky** [ktquez/vue-disqus#6]
Hi. Good job on vue-disqus.

I have 2 suggestions though.
Can you please follow the standard and create /dist folder where you put you ready to use generated files?
vue-disqus/dist/vue-disqus.js

And second, can you include minified version in dist as well?
vue-disqus/dist/vue-disqus.min.js

**Comment by ktquez** [comment]
Sorry for my delay.
I will refactor and create dist files for ES6, AMD and commonJS.

**Comment by ktquez** [comment]
@maxorlovsky 
Late, but left.
It is supported for (AMD, UMD, ES6, CJS)

Thanks for idea.
