### ISSUE TITLE
Some questions of integration vue-disqus

### ISSUE THREAD

**Issue by TangoPJ** [ktquez/vue-disqus#66]
Hi there!
I have several questions:
1. After intergrating vue-disqus on my website, will users be able to leave comments after registering, or everyone be able to?
2. Are users comments stored in Disqus or on my site?
3. Can I change the styling of the component to suit my site design?

**Comment by ktquez** [comment]
Hi @TangoPJ 

1. Anonymous/guest commented is no longer supported
2. Disqus server
3. I think not

**Comment by TangoPJ** [comment]
@ktquez Hi, thank you for answers :)
