### ISSUE TITLE
Emit event when ready

### ISSUE THREAD

**Issue by adam-lynch** [ktquez/vue-disqus#7]
We need to know when this is ready, so we can show a placeholder or whatever before it is. According to [this article](https://www.electrictoolbox.com/running-javascript-functions-after-disqus-loaded/), you could pass an `afterRender` callback and then emit an event? If you're OK with this, I could create a pull-request.

**Comment by ktquez** [comment]
@adam-lynch 
Yes!
You can send, I accept your pull-request here.
This is very good, thanks for this.
