### ISSUE TITLE
UglifyJS errors with 2.0.4

### ISSUE THREAD

**Issue by scottbedard** [ktquez/vue-disqus#9]
After upgrading to `2.0.4`, I'm receiving the following error when I try to build [this repo](https://github.com/scottbedard/scottbedard.net). Reverting to `2.0.3` seems to still work as expected.

```bash
ERROR in static/js/vendor.423f6bff34d8d6bca52a.js from UglifyJs
SyntaxError: Unexpected token: punc ()) [./~/vue-disqus/vue-disqus.js:70,0]
```

**Comment by ktquez** [comment]
This problem should be in the vue-template

**Comment by wsdo** [comment]
not resolved
